"""empty message

Revision ID: 084bae439dd3
Revises: 851f6717b627
Create Date: 2020-04-29 09:11:47.258982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084bae439dd3'
down_revision = '851f6717b627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
